MVCClient/Models/ErrorViewModel.cs
using System;

namespace MVCClient.Models
{
   public class ErrorViewModel
   {
      public string RequestId { get; set; }

      public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
   }
}

MVCClient/Controllers/AjaxController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVCClient.Controllers
{
   public class AjaxController : Controller
   {
      // GET: AjaxController
      public ActionResult Index()
      {
         return View();
      }

      // GET: AjaxController/Details/5
      public ActionResult Details(int id)
      {
         return View();
      }

      // GET: AjaxController/Create
      public ActionResult Create()
      {
         return View();
      }

      // POST: AjaxController/Create
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create(IFormCollection collection)
      {
         try
         {
            return RedirectToAction(nameof(Index));
         }
         catch
         {
            return View();
         }
      }

      // GET: AjaxController/Edit/5
      public ActionResult Edit(int id)
      {
         return View();
      }

      // POST: AjaxController/Edit/5
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit(int id, IFormCollection collection)
      {
         try
         {
            return RedirectToAction(nameof(Index));
         }
         catch
         {
            return View();
         }
      }

      // GET: AjaxController/Delete/5
      public ActionResult Delete(int id)
      {
         return View();
      }

      // POST: AjaxController/Delete/5
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Delete(int id, IFormCollection collection)
      {
         try
         {
            return RedirectToAction(nameof(Index));
         }
         catch
         {
            return View();
         }
      }
   }
}

MVCClient/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCClient.Controllers
{
   public class CustomersController : Controller
   {
      public IActionResult Index()
      {
         return View();
      }
      public IActionResult CustomerInfo()
      {
         return View();
      }
      public IActionResult DatatablesView()
      {
         return View();
      }
      public IActionResult BootstrapView()
      {
         return View();
      }
      
   }
}

MVCClient/Controllers/DemoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVCClient.Controllers
{
   public class DemoController : Controller
   { 
      public ActionResult Index()
      {
         return View();
      }
       
      public ActionResult Details(int id)
      {
         return View();
      }
       
      public ActionResult Create()
      {
         return View();
      }
       
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create(IFormCollection collection)
      {
         try
         {
            return RedirectToAction(nameof(Index));
         }
         catch
         {
            return View();
         }
      }
       
      public ActionResult Edit(int id)
      {
         return View();
      } 
      [ValidateAntiForgeryToken]
      public ActionResult Edit(int id, IFormCollection collection)
      {
         try
         {
            return RedirectToAction(nameof(Index));
         }
         catch
         {
            return View();
         }
      }

      // GET: DemoController/Delete/5
      public ActionResult Delete(int id)
      {
         return View();
      }

      // POST: DemoController/Delete/5
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Delete(int id, IFormCollection collection)
      {
         try
         {
            return RedirectToAction(nameof(Index));
         }
         catch
         {
            return View();
         }
      }
   }
}

MVCClient/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCClient.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCClient.Controllers
{
   public class HomeController : Controller
   {
      private readonly ILogger<HomeController> _logger;

      public HomeController(ILogger<HomeController> logger)
      {
         _logger = logger;
      }

      public IActionResult Index()
      {
         return View();
      }

      public IActionResult Privacy()
      {
         return View();
      }
      public IActionResult RemoveJquery()
      {
         return View();
      }
      [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
      public IActionResult Error()
      {
         return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
      }
        public IActionResult Report()
        {
            return View();
        }
   }
}

MVCClient/Controllers/OfficeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVCClient.Controllers
{
   public class OfficeController : Controller
   {
      [AllowAnonymous]
      public IActionResult Index()
      {
         return View();
      }
   }
}

MVCClient/Views/Ajax/Index.cshtml
@*<html>
<head>

   <link src="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet"/>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script>
      $(document).ready(function () {
         $('#example').DataTable({
            ajax: '~/datasource/arrays.txt',
         });
      });
      </script>
   </head>
   <body>
   <table id="example" class="display" style="width:100%">
      <thead>
         <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Office</th>
            <th>Extn.</th>
            <th>Start date</th>
            <th>Salary</th>
         </tr>
      </thead>
      <tfoot>
         <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Office</th>
            <th>Extn.</th>
            <th>Start date</th>
            <th>Salary</th>
         </tr>
      </tfoot>
   </table>
   </body>
</html>*@
<!DOCTYPE html>
   <html>
   <head>
      @*<a href="~/datasource/arrays.json">~/datasource/arrays.json</a>*@
      <title>jQuery Function</title>
      @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>*@
      @*<script src="js/jquery.min.js" type="text/javascript"></script>
      <script src="js/jquery.dataTables.min.js" type="text/javascript"></script>*@

      <script src="~/DataSource/data.json"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
   <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />

   <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
   <script src="~/js/min.js"></script>
      <script>
         //$(document).ready(function () {
         //   $('#example').DataTable({
         //            //--"ajax": "data.json"
         //      "ajax": '~/datasource/arrays.json',
         //   });
         //});
         //$('#example').dataTable({
         //   "ajax": {
         //      "url": "~/datasource/data.json",
         //      "type": "GET"
         //   }
         //});
      </script>
   </head>

   <body>
      <div id="mydiv">
         <table id="example" class="display" style="width:100%">
            <thead>
               <tr>
                  <th>Name</th>
                  <th>Position</th>
                  <th>Office</th>
                  <th>Extn.</th>
                  <th>Start date</th>
                  <th>Salary</th>
               </tr>
            </thead>
            <tfoot>
               <tr>
                  <th>Name</th>
                  <th>Position</th>
                  <th>Office</th>
                  <th>Extn.</th>
                  <th>Start date</th>
                  <th>Salary</th>
               </tr>
            </tfoot>
         </table>
      </div>
   </body>
</html>

MVCClient/Views/Customers/BootstrapView.cshtml
<!doctype html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <!-- CSS Stylesheets -->
   <link href="/RetailSmart/Jquery/jquery.multiselect.css" rel="stylesheet" />
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
         integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   <style>
      .jumbotron {
         border-radius: 0%;
      }

      h1 {
         color: aquamarine;
      }

      #lab {
         color: azure;
         font-size: 1.5em;
      }

      p {
         color: azure;
      }

      #bot {
         color: antiquewhite;
      }
   </style>
   <title>rito-weather</title>
</head>

<body>
   <div class="jumbotron bg-secondary">
      <div class="container">
         <h1>
            Weather App <svg class="bi bi-lightning-fill" width="1em" height="1em" viewBox="0 0 16 16"
                             fill="currentColor" xmlns="http://www.w3.org/2000/svg">
               <path fill-rule="evenodd"
                     d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z" />
            </svg>
         </h1>
         <form id="form-sub">
            <div class="form-group ">
               <label id="lab" for="lab">City :</label>
               <input type="text" class="form-control" id="city" placeholder="ex. London...">
               <small id="bot" class="form-text">Fill city name for weather details.</small>
               <button type="submit" class="btn btn-primary mt-3">
                  <svg class="bi bi-search" width="1em" height="1em"
                       viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                     <path fill-rule="evenodd"
                           d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                     <path fill-rule="evenodd"
                           d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                  </svg> Submit
               </button>
            </div>
         </form>
         <hr>
         <p id="city-name" class="mr-3"></p>
         <p id="city-weather"></p>
         <img src="">
         <p id="city-temp"></p>
      </div>
   </div>


   <!-- JQuery Scripts -->
   <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js"
       integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script> -->
   <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"
       integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
   <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
   <!-- Our codes -->
   <script src="~/js/script.js"></script>
   <script src="/bundle.js"></script>
   </body>
</html>

MVCClient/Views/Customers/CustomerInfo.cshtml
@{
   ViewBag.Title = "Index";
   //Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>All ClassName</h2>
<div class="float-r">
   <button style="font-size:20px;" title="Add Customers" id="btnModal"
           data-toggle="modal" data-target="#MyModal">
      @*<i class="fa fa-plus"></i>*@
      Add<br />
   </button>
</div>
<table class="table table-bordered" id="tble">

   <thead>
      <tr>
         <td>SL NO</td>
         <td>CustomerName</td>
         <td>PurchasesProduct</td>
         <td>PaymentType</td>
         <td>Edit</td>
         <td>Delete</td>
      </tr>
   </thead>
   <tbody>
   </tbody>
</table>

<div class="modal fade" id="MyModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal"
                    aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <div class="form-group">
               <label>ID</label>
               <input type="number" id="txtId" hidden />
               <label>CustomerName</label>
               <input type="text" class="form-control" id="txtCustomerName" />
            </div>
            <div class="form-group">
               <label>PurchasesProduct</label>
               <input type="text" class="form-control" id="txtPurchasesProduct" />
            </div>
            <div class="form-group">
               <label>PaymentType</label>
               <input type="text" class="form-control" id="txtPaymentType" />
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="btnSave">Save changes</button>
            <button type="button" class="btn btn-primary" onclick="Update()" id="btnUpdate">Update changes</button>

         </div>
      </div>
   </div>
</div>
@section scripts{
   <script src="~/js/site.js"></script>
}

MVCClient/Views/Customers/Index.cshtml
@{
   ViewBag.Title = "Index";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All ClassName</h2>
<div class="float-r">
   <button style="font-size:20px;" title="Add Customers" id="btnModal"
           data-toggle="modal" data-target="#MyModal">
      @*<i class="fa fa-plus"></i>*@
      Add<br />
   </button>
</div>
<table class="table table-bordered" id="tble">

   <thead>
      <tr>
         <td>CustomerName</td>
         <td>PurchasesProduct</td>
         <td>PaymentType</td>
         <td>Edit</td>
         <td>Delete</td>
      </tr>
   </thead>
   <tbody>
   </tbody>
</table>

<div class="modal fade" id="MyModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal"
                    aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <div class="form-group">
               <label>ID</label>
               <input type="number" id="txtId" hidden />
               <label>CustomerName</label>
               <input type="text" class="form-control" id="txtCustomerName" />
            </div>
            <div class="form-group">
               <label>PurchasesProduct</label>
               <input type="text" class="form-control" id="txtPurchasesProduct" />
            </div>
            <div class="form-group">
               <label>PaymentType</label>
               <input type="text" class="form-control" id="txtPaymentType" />
            </div>
            @*<div class="form-group">
               <label>CreatedDate</label>
               <input type="date" class="form-control" id="txtCreatedDate" />
            </div>
            <div class="form-group">
               <label>ModifiedDate</label>
               <input type="date" class="form-control" id="txtModifiedDate" />
            </div>
            <div class="form-group">
               <label>check</label>
               <input type="checkbox" class="form-control" value="1" id="check" />
            </div>*@
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="btnSave">Save changes</button>
            <button type="button" class="btn btn-primary" onclick="Update()" id="btnUpdate">Update changes</button>

         </div>
      </div>
   </div>
</div>


@section scripts{
   <script>
      $(document).ready(function () {
         $("#btnUpdate").hide();
         //$("#MyModal").modal('hide');
         $("#btnSave").show();
         var IsEdit = false;
         $("#MyModal").modal({
            backdrop: 'static',
            keyboard: false
            /*show: true*/
         });
         load()
         //$('#MyModal').modal({
         //        backdrop: 'static',
         //    keyboard: true,
         //    show: false
         //    });
         $("#btnModal").click(function () {
            $("#MyModal").modal('show')
            //$('#MyModal').modal({
            //    backdrop: 'static',
            //    keyboard: true,
            //    show: true
            //});

         })
         $("#btnSave").click(function () {
            var customer = {
               id: $('#txtId').val(),
               //createdDate: $('#txtCreatedDate').val(),
               //modifiedDate: $('#txtModifiedDate').val(),
               //isActive: $('#check').val(),
               CustomerName: $("#txtCustomerName").val(),
               PurchasesProduct: $("#txtPurchasesProduct").val(),
               PaymentType: $("#txtPaymentType").val()
               
            }
            console.log(customer)
            //console.log($(id);
            $.ajax({
               
               url: "https://localhost:44395/api/Customer/InsertCustomer",
               type: "JSON",
               method: "POST",
               data: JSON.stringify(obj),
               contentType: "application/json",
               success: function (result) {
                  console.log(result)
                  $("#MyModal").modal('hide')
                  clearALl(); 
                  load();
               },
               error: function (er) {
                  console.log(er)
               }
            })
         })
         //$("#btnUpdate").click(function () {

         //}

      })
      function clearALl() {
            $("#txtCustomerName").val(''),
            $("#txtPurchasesProduct").val(''),
            $("#txtPaymentType").val(''),
            $('#txtCreatedDate').val(''),
            $('#txtModifiedDate').val(''),
            $('#check').val(''),
            $("#txtId").empty()
      }
      function Close() {
         //alert(IsEdit);
         //if (IsEdit == false) {
         $("#MyModal").modal('hide');

         clearALl();
         // }
      }
      function load() {
         $.ajax({
            url: "https://localhost:44395/api/Customer/GetAllCustomer",
            type: "JSON",
            method: "GET",
            success: function (result) {
               console.log(result)
               $("#tble tbody").empty();
               $.each(result, function (i, v) {
                  console.log(v)
                  var html = "<tr><td>" + v.customerName + "</td>" +
                     "<td>" + v.purchasesProduct + "</td>" +
                     " <td>" + v.paymentType + "</td>" +
                     " <td> <button onClick='Edit(" + v.id + ")'>Edit </button></td>" +
                     " <td> <button onClick='Delete(" + v.id + ")'>Delete </button></td></tr>";

                  $("#tble tbody").append(html)
               })
            },
            error: function (er) {
               console.log(er)
            }
         })
      }

      function Edit(id) {
         alert(id)
         $("#btnUpdate").show();
         $("#btnSave").hide();

         $.ajax({
            url: "https://localhost:44395/api/Customer/UpdateCustomer/"+id,
            type: "JSON",
            method: "GET",
            success: function (result) {
               $("#exampleModalLabel").html("Update Department Information");
               console.log(result)
               IsEdit = true;

               $("#txtCustomerName").val(result.customerName),
                  $("#txtPurchasesProduct").val(result.purchasesProduct),
                  $("#txtPaymentType").val(result.paymentType)
               $("#txtId").val(result.id)
               $("#MyModal").modal('show')
            },
            error: function (er) {
               console.log(er)
            }
         })

      }
      function Update() {
         alert($("#txtId").val());
         var url = "https://localhost:44395/api/Customer/UpdateCustomer/" + $("#txtId").val();
         var object = {
            ClassesName: $("#txtCustomerName").val(),
            ShortName: $("#txtPurchasesProduct").val(),
            Description: $("#txtPaymentType").val(),
            Id: $("#txtId").val()
         }
         $.ajax({
            url: url,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            type: "Put",

            data: JSON.stringify(object),
            success: function (result) {
               //getProductData();
               //clear();
               $("#MyModal").modal('hide');
               load();
               clearALl();
               console.log("....")
               console.log(result)
               //if (result > 0 ) {
               //    load();
               //    clearALl();

               //}
               $("#btnUpdate").hide();
               $("#btnSave").show();
            },
            error: function (er) {
               console.log(er.responseText);
            }
         })
      }
      //function Update() {
      //    $.ajax({
      //        url: "https://localhost:44372/api/Departments/",
      //        type: "JSON",
      //        method: "PUT",
      //        data: { Name: $("#txtName").val(), ShortName: $("#txtSName").val(), Description: $("#txtDescription"), Id: $("#txtId").val() },
      //        success: function (result) {
      //            console.log(result)
      //            if (result.Id > 0) {
      //                load();
      //                clearALl();
      //            }
      //        },
      //        error: function (er) {
      //            console.log(er.responseText);
      //        }
      //    })
      //}
      function Delete(id) {
         alert(id);
         var url = "https://localhost:44395/api/Customer/DeleteCustomer/" + id;
         $.ajax({
            url: url,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            type: "Delete",
            success: function (result) {
               clearALl();
               alert(result);
               load();
            },
            error: function (msg) {
               alert(msg);
            }
         });
      }
   </script>
}

MVCClient/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8" />
   <title>Kendo UI Snippet</title>

   <link rel="stylesheet" href="https://kendo.cdn.telerik.com/themes/6.3.0/default/default-ocean-blue.css" />

   <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
   <script src="https://kendo.cdn.telerik.com/2023.1.425/js/kendo.all.min.js"></script>
</head>
<body>
   <h1>My CryptoCurrency Dashboard</h1>
   <div id="splitter">
      <div id="left-pane"><div id="tabs"></div></div>
      <div id="right-pane">
         <h3> Trading Pair :<span id="trading-pair"></span></h3>
         <input id="picker"/>
         <div id="button-group"></div>
         <div id="chart"></div>
         <div id="picker"></div>

      </div>
   </div>
   <script>
      $('#chart').kendoChart({
         tooltip:{
            visible:true,
         },
         legend:{
            poistion:'bottom'
         },
         series:[{
            name:'Last Price',
            field:'Price',
            type:'line',
            style:'normal',
            markers:{
               visible:false,
            }
         }]
      });
      $('#picker').kendoDateTimePicker({
         dateInput:true,
         format:'MM/dd/yyyy h tt',
         interval:60,
         value:new Date(),
         disableDate:function(date){
            var now = new Date();
            if(date>now){
               return true;
            }
            else{
               return false;
            }
         },
         change:function(){
            var time = this.value().getTime();
            var now = new Date().getTime();
            var hours = Math.round((now -time)/3.6e6)
            updateChart(tradingPair,hours);
         }
      })
   </script>
</body>
</html>

MVCClient/Views/Home/RemoveJquery.cshtml
<!DOCTYPE HTML>
<html>
<head>

	<title>
		How to remove a table row
		from table
	</title>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js">
	</script>

	<style>
		#myCol {
			background: green;
		}

		table {
			color: white;
		}

		#Geek_p {
			color: green;
			font-size: 30px;
		}

		td {
			padding: 10px;
		}
	</style>
</head>

<body>
	<center>
		<h1 style="color:green;">
			GeeksForGeeks
		</h1>

		<table>
			<colgroup>
				<col id="myCol"
					  span="2">
				<col style="background-color:green">
			</colgroup>

			<tr>
				<th>S.No</th>
				<th>Title</th>
				<th>Geek_id</th>
			</tr>
			<tr id="row1">
				<td>Geek_1</td>
				<td>GeekForGeeks</td>
				<th>Geek_id_1</th>
			</tr>
			<tr>
				<td>Geek_2</td>
				<td>GeeksForGeeks</td>
				<th>Geek_id_2</th>
			</tr>
		</table>
		<br>

		<button onclick="Geeks()">
			Click here
		</button>

		<!-- Script to remove table row from table -->
		<script>
			function Geeks() {
				$("#row1").remove();
			}
		</script>
	</center>
</body>
</html>

MVCClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCClient</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="CustomerInfo">Customer Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Office" asp-action="Index">Office</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCClient/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @@Styles.Render("~/Content/css")
    @@Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'" onerror="this.removeAttribute('data-rocket-async')"  rel="preload" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Register", "Index", "Employee", null, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>jQuery ajax - Asp.Net MVC CRUD Operations</p>
        </footer>
    </div>
    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>
    @@Scripts.Render("~/bundles/jquery")
    @@Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/Scripts.js" defer></script>
    </body>
  </html>